### ISSUE TITLE
See the report

### ISSUE THREAD

**Issue by Sohadwd** [FACG2/Inventory-Management-System#12]
- [x] Add report button and redirect to the report (1h)
- [x] Get the data from the database (6h)
- [x] Add install button to the report (h1)
- [x] Style (3h)
- [x] Testing (4h)

**Comment by SamerElaila** [comment]
![transactions](https://user-images.githubusercontent.com/19314445/30535614-9dc1c8fa-9c6b-11e7-93b5-97e7f8a73d18.png)
