### ISSUE TITLE
User Journey

### ISSUE THREAD

**Issue by Sohadwd** [FACG2/Inventory-Management-System#3]
- [x] Sign Up to the app. https://github.com/FACG2/Inventory-Management-System/issues/4
- [x] Login to the app. https://github.com/FACG2/Inventory-Management-System/issues/6
- [x] Open my inventory page. https://github.com/FACG2/Inventory-Management-System/issues/16
- [ ] See goods status in my inventory. https://github.com/FACG2/Inventory-Management-System/issues/15
- [x] Add new type goods to the inventory.  https://github.com/FACG2/Inventory-Management-System/issues/7
- [x] See the report. https://github.com/FACG2/Inventory-Management-System/issues/12
- [x] See the graphs. https://github.com/FACG2/Inventory-Management-System/issues/14
- [x] Edit Goods. https://github.com/FACG2/Inventory-Management-System/issues/18
- [x] Delete Goods. https://github.com/FACG2/Inventory-Management-System/issues/19
- [x] Logout. https://github.com/FACG2/Inventory-Management-System/issues/17
