### ISSUE TITLE
Login 

### ISSUE THREAD

**Issue by Sohadwd** [FACG2/Inventory-Management-System#6]
- [x] Take email and check against the database (4h)
- [x] Check password with hashed password in the database (2h)
- [x] Redirect to the home page (1h)
- [x] Style (1h)
- [x] Testing (3h)

**Comment by SamerElaila** [comment]
![sign in](https://user-images.githubusercontent.com/19314445/30535484-3786290a-9c6b-11e7-947f-5aeafa8f2d99.png)
