### ISSUE TITLE
Add a new goods

### ISSUE THREAD

**Issue by Sohadwd** [FACG2/Inventory-Management-System#7]
- [x] Add new goods button and redirect new goods (1h)
- [x] Create a new view (4h)
- [x] User input added to the database (6h)
- [x] Redirect to goal viewing page (1h)
- [x] Style (3h)
- [x] Testing (4h)

**Comment by SamerElaila** [comment]
![add new good](https://user-images.githubusercontent.com/19314445/30535589-873a0390-9c6b-11e7-8270-59dc0effee08.png)
